### ISSUE TITLE
the view is not moved when publising assets

### ISSUE THREAD

**Issue by crissi** [yondifon/laravel-graphiql#15]

**Comment by crissi** [comment]
sidequestion:
https://github.com/OneGraph/graphiql-explorer does this support this view?
![image](https://user-images.githubusercontent.com/3076578/191264153-8539fbd1-02e1-4323-8c80-941084ecd190.png)

**Comment by crissi** [comment]
https://github.com/yondifon/laravel-graphiql/blob/main/resources/views/graphiql.blade.php

this is never moded on asset publish so, you have not change to edit it yourself?

so could be nice for it to moved or a way to use your own though the config

**Comment by yondifon** [comment]
Hey @crissi. How do you mean?

**Comment by crissi** [comment]
if I want to add my own logic to the [graphiql.blade.php](https://github.com/yondifon/laravel-graphiql/blob/main/resources/views/graphiql.blade.php).I can't since the file is moved to the resource on **artisan vendor:publish**

One way is to move another way is to make it possible to set a path to your view
