### ISSUE TITLE
view refereres to config('lighthouse.route.name')

### ISSUE THREAD

**Issue by crissi** [yondifon/laravel-graphiql#16]
should probably point to somewhere in the graphiql config

**Comment by yondifon** [comment]
@crissi How do you mean?

**Comment by yondifon** [comment]
I don't quite get what you mean but this package is independent of lighthouse.

**Comment by yondifon** [comment]
I'll push for it.

**Comment by yondifon** [comment]
Thanks @crissi. Just pushed the fix.

**Comment by crissi** [comment]
thank will give it a try again
